title = "Pure Pandemonium Podcast"
baseURL = "https://www.pure-pandemonium.club/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The website of the Pure Pandemonium Podcast"
  facebook = ""
  twitter = "https://twitter.com/PandemoniumPure"
  # instagram = ""
  # youtube = ""
  # github = ""
  # gitlab = ""
  # linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-moon-gray"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
